### PR TITLE
Add Comment / Change IF statement / Define $speed var

### PR DESCRIPTION
**Pull request by benda95280**

### CODE REVIEW

**Comment by Saxavlax001** [comment]
Wait @benda95280 ill fix the pr

**Comment by benda95280** [comment]
Sorry, My Text formatter and my eyes do crazy thing, i'm going to try it.

**Comment by Saxavlax001** [comment]
Merged

**Comment by Saxavlax001** [comment]
I think

**Comment by Saxavlax001** [comment]
Ok no errors in poggit too.

**Comment by Saxavlax001** [comment]
@benda95280 sorry for that chaos,I fixed an error on your code too,you can test it if you want,use latest source.

**Comment by benda95280** [comment]
No problem, i've done a little modification, and work from source on PM, but i'm alone on my server ... 😭

**Comment by Saxavlax001** [comment]
Do you have discord?Also the player stops now when he comes close to the other player.

**Comment by benda95280** [comment]
Hello, yes i've a discord, but not so availaible to discuss.
I've try with a Bot plugin, but nothing happen.

The player stop, and can't move at all ?
Seems right, because if you'r too close, event is canceled

I've some idea:
- Change level of knockback, runing fast = more knockback (Seems easy, need to know value at max speed when walking, and when runing)
- Need to add a check that your looking to the player in front of you, if you'r not looking at him, you can continue to walk

**Comment by benda95280** [comment]
I'm trying to get speed when walking and running, but my script crash.
         **echo (abs($player->getMotion()->x) + abs($player->getMotion->z)). "  -  ";**
_[21:09:43] [Server thread/CRITICAL]: ErrorException: "Undefined property: pocketmine\Player::$getMotion" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 2257_

I'm a little busy toningh, will check that tomorrow :)

**Comment by Saxavlax001** [comment]
Ok👍,also its getMotion() not getMotion.

**Comment by benda95280** [comment]
🤦‍♂

**Pull request closed without merging**
